on:
  push:
    branches:
    - develop

name: Develop
jobs:

  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ADMIN_TOKEN_GITHUB }}

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.ADMIN_TOKEN_GITHUB }}
        git-user-name: github-actions
        output-file: "false"

    - name: Install
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      run:
        npm install

    - name: Build
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      run:
        npm run ci:build

    - name: Publish
      uses: netlify/actions/cli@master
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      with:
        args: deploy --prod --dir=demo
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN_GITHUB }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
        prerelease: true
