on:
  push:
    tags-ignore:
      - v*
    branches:
      - develop

name: Develop
jobs:

  release:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ADMIN_TOKEN_GITHUB }}

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install
      run:
        npm install

    - name: Build libraries
      run:
        npm run ci:build-libs

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        config-file-path: .github/tools/changelog-config.js
        github-token: ${{ secrets.ADMIN_TOKEN_GITHUB }}
        output-file: "false"
        skip-on-empty: "false"

    - name: Translate
      run:
        npm run ci:translate

    - name: Sync translations
      run:
        npm run ci:sync-translations
      env:
        POEDITOR_API_KEY: ${{ secrets.POEDITOR_API_KEY }}

    - name: Build
      run:
        npm run ci:build

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod --dir=dist/demo
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    - name: Create Github Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN_GITHUB }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
        prerelease: false

    - name: Create Sentry Release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        SENTRY_LOG_LEVEL: debug
      with:
        environment: production
        version: ${{ steps.changelog.outputs.tag }}
        sourcemaps: './dist/demo'
