on: pull_request
name: Build Angular
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install
      run:
        npm install

    - name: Lint
      run:
        npm run ci:lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install
      run:
        npm install

    - name: Test
      run:
        npm run ci:test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install
      run:
        npm install

    - name: Build
      run:
        npm run ci:build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: dist

  preview:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: artifacts

    - name: Debug
      shell: bash
      run: ls -l

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=dist/demo
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
